/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managr;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 * Home screen class Swing GUI
 * @author Andy
 * @since JDK 7u80
 * @version 7.0
 */
public class HomeScreen extends javax.swing.JFrame {

    
    /**
     * Constructor that creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
    }
    
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        taskListButton = new javax.swing.JButton();
        calendarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        todayTaskDisplay = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        todayStudyDisplay = new javax.swing.JTextPane();
        todayScheduleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(921, 572));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Home");

        taskListButton.setText("Task Management");
        taskListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskListButtonActionPerformed(evt);
            }
        });

        calendarButton.setText("Calendar View");
        calendarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Today's Tasks Listed In Order of Priority Based on Due Date and Weighted Importance:");

        jScrollPane1.setViewportView(todayTaskDisplay);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Today's Scheduled Study Sessions: ");

        jScrollPane2.setViewportView(todayStudyDisplay);

        todayScheduleButton.setText("View Today's Events");
        todayScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayScheduleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(taskListButton)
                                .addGap(132, 132, 132)
                                .addComponent(todayScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addComponent(calendarButton)))
                        .addGap(84, 84, 84)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calendarButton)
                    .addComponent(taskListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todayScheduleButton))
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
 * Method to open calendar view
 * @param evt the calendar button is pressed
 */
    private void calendarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarButtonActionPerformed
        // TODO add your handling code here:
        Calendrier cal = new Calendrier();
        cal.setVisible(true);
        dispose();
    }//GEN-LAST:event_calendarButtonActionPerformed
/**
 * Method to open taskList view
 * @param evt the task list button is pressed
 */
    private void taskListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskListButtonActionPerformed
        // TODO add your handling code here:
        TasksArea area = new TasksArea();
        area.setVisible(true);
        dispose();
    }//GEN-LAST:event_taskListButtonActionPerformed
    /**
     * Method responding to user pressing the todayScheduleButton, displays all the studies and tasks scheduled for the current day
     * @param evt the today schedule button is clicked.
     */
    private void todayScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayScheduleButtonActionPerformed
        // TODO add your handling code here:
        //retrieves tasks due today
         ArrayList<Task> todaysTasks = HomeScreenController.getTodaysTasks();
         //retrieves studies sscheduled for today
            ArrayList<Study> todaysStudies = HomeScreenController.getTodaysStudies();
            String displayStudies = "";
            String displayString = "";
            SimpleDateFormat formatter = new SimpleDateFormat("HH:mm");
            //displays all tasks due today on text panel
            for(int i = 0; i < todaysTasks.size(); i++){
                
                String name = ((Task)todaysTasks.get(i)).getName(); 
                String type = ((Task)todaysTasks.get(i)).getTaskType(); 
                String subject = ((Task)todaysTasks.get(i)).getSubject(); 
                Date date = ((Task)todaysTasks.get(i)).getDueDate();
             
                String time = formatter.format(date);
                //if the task is already past due, displays ALREADY PAST DUE in from of task info
                if(((Task)todaysTasks.get(i)).urgency() <0 ){
                displayString = displayString + "ALREADY PAST DUE Name: " +name + "     Type: " + type + "     Subject: " + subject +"     Due at: "+time+"\n";
                }
                else{
                displayString = displayString + "Name: " +name + "     Type: " + type + "     Subject: " + subject +"     Due at: "+time+"\n";                
                }
             }
            //displays all study sessions scheduled for today on text panel
            for(int j = 0; j < todaysStudies.size(); j++){
                String subject = ((Study)todaysStudies.get(j)).getSubject();
                int length = ((Study)todaysStudies.get(j)).getHours();
                String hr = ((Study)todaysStudies.get(j)).getStudyHour();
                String min = ((Study)todaysStudies.get(j)).getStudyMin();
                displayStudies = displayStudies + "Subject: "+subject+"     Length of study session (hrs): "+length+"     Start Time: "+hr+":"+min+"\n";
            }
            todayTaskDisplay.setText(displayString);
            todayStudyDisplay.setText(displayStudies);
    }//GEN-LAST:event_todayScheduleButtonActionPerformed
  
    
    /**
     * Main method
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new HomeScreen().setVisible(true);
                
                //hs.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calendarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton taskListButton;
    private javax.swing.JButton todayScheduleButton;
    private javax.swing.JTextPane todayStudyDisplay;
    private javax.swing.JTextPane todayTaskDisplay;
    // End of variables declaration//GEN-END:variables
}
